"""OpenRouter-compatible LLM client using the OpenAI Responses API.

The Responses API is the newer OpenAI surface (non-beta structured outputs).
Confirmed working against OpenRouter + `anthropic/claude-sonnet-4.6`.
"""
from __future__ import annotations

from typing import TypeVar

from openai import (
    APIConnectionError, APITimeoutError, InternalServerError,
    OpenAI, RateLimitError,
)
from pydantic import BaseModel
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential


OPENROUTER_BASE = "https://openrouter.ai/api/v1"


T = TypeVar("T", bound=BaseModel)


# Only retry on transient network / rate-limit / 5xx errors.
# Schema mismatches, auth errors, malformed requests surface immediately.
_TRANSIENT = (APIConnectionError, APITimeoutError, RateLimitError, InternalServerError)

_retry = retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=1, max=10),
    retry=retry_if_exception_type(_TRANSIENT),
)


class LLMClient:
    def __init__(
        self,
        api_key: str,
        model: str,
        base_url: str = OPENROUTER_BASE,
        reasoning_effort: str | None = None,
    ):
        self.model = model
        # When set, `chat_structured` sends `reasoning={"effort": ...}` and
        # omits `temperature` (reasoning models reject sampling params).
        self.reasoning_effort = reasoning_effort
        self._client = OpenAI(base_url=base_url, api_key=api_key)

    def _build_kwargs(
        self,
        messages: list[dict],
        temperature: float,
        max_tokens: int | None,
    ) -> dict:
        kwargs: dict = {
            "model": self.model,
            "input": messages,
        }
        if max_tokens is not None:
            kwargs["max_output_tokens"] = max_tokens
        if self.reasoning_effort is not None:
            kwargs["reasoning"] = {"effort": self.reasoning_effort}
        else:
            kwargs["temperature"] = temperature
        return kwargs

    @_retry
    def chat(
        self,
        messages: list[dict],
        temperature: float = 0.2,
        max_tokens: int | None = None,
    ) -> str:
        """Plain text completion via the Responses API."""
        resp = self._client.responses.create(
            **self._build_kwargs(messages, temperature, max_tokens)
        )
        return resp.output_text or ""

    @_retry
    def chat_structured(
        self,
        messages: list[dict],
        response_model: type[T],
        temperature: float = 0.0,
        max_tokens: int | None = None,
    ) -> T:
        """Structured completion via the Responses API with strict JSON Schema.

        Uses `responses.parse()` — the non-beta structured-output path.
        Pydantic model → JSON schema is generated by the SDK; provider returns
        validated JSON; SDK parses into the typed model.
        """
        resp = self._client.responses.parse(
            **self._build_kwargs(messages, temperature, max_tokens),
            text_format=response_model,
        )
        parsed = resp.output_parsed
        if parsed is None:
            raise ValueError(
                f"LLM returned no parsed output (refusal or schema mismatch). "
                f"Raw: {getattr(resp, 'output_text', None)!r}"
            )
        return parsed
